# Set configuration defaults. This schema describes the cron_orders.settings
# config. The defaults for this config are set in
# config/install/cron_orders.settings.yml and then used by
# \Drupal\cron_orders\Form\CronOrdersForm.
# @see https://www.drupal.org/node/1905070
cron_orders.settings:
  type: config_object
  label: 'Cron Example settings'
  mapping:
    interval:
      type: integer
      label: 'Period between cron runs'
